name: Manual Scrape & Build Leaderboard

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Select the job to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - codechef
          - codeforces
          - geeksforgeeks
          - hackerrank
          - leetcode

env:
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  GFG_USERNAME: ${{ secrets.GFG_USERNAME }}
  GFG_PASSWORD: ${{ secrets.GFG_PASSWORD }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  CODECHEF_CLIENT_ID: ${{ secrets.CODECHEF_CLIENT_ID }}
  CODECHEF_CLIENT_SECRET: ${{ secrets.CODECHEF_CLIENT_SECRET }}
  CODEFORCES_KEY: ${{ secrets.CODEFORCES_KEY }}
  CODEFORCES_SECRET: ${{ secrets.CODEFORCES_SECRET }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      needs: ${{ steps.setup.outputs.needs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  batch1:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        job: [codechef, codeforces, geeksforgeeks, hackerrank, leetcode]
    steps:
      - name: Scrape Batch 1
        run: |
          if [[ "${{ github.event.inputs.job }}" == "all" || "${{ matrix.job }}" == "${{ github.event.inputs.job }}" ]]; then
            python main.py --batch 1 --scrape ${{ matrix.job }}
          fi
  
  batch1-evaluate:
    runs-on: ubuntu-latest
    needs: [setup, batch1]
    steps:
      - name: Evaluate Batch 1
        run: |
          python main.py --batch 1 --evaluate

  batch2:
    runs-on: ubuntu-latest
    needs: [setup, batch1]
    strategy:
      matrix:
        job: [codechef, codeforces, geeksforgeeks, hackerrank, leetcode]
    steps:
      - name: Scrape and Evaluate Batch 2
        run: |
          if [[ "${{ github.event.inputs.job }}" == "all" || "${{ matrix.job }}" == "${{ github.event.inputs.job }}" ]]; then
            python main.py --batch 2 --scrape ${{ matrix.job }}
          fi

  batch2-evaluate:
    runs-on: ubuntu-latest
    needs: [setup, batch2]
    steps:
      - name: Evaluate Batch 2
        run: |
          python main.py --batch 2 --evaluate
