name: Manual Verify & Upload Users

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Choose which job to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - codechef
          - codeforces
          - geeksforgeeks
          - hackerrank
          - leetcode

env:
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  GFG_USERNAME: ${{ secrets.GFG_USERNAME }}
  GFG_PASSWORD: ${{ secrets.GFG_PASSWORD }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  CODECHEF_CLIENT_ID: ${{ secrets.CODECHEF_CLIENT_ID }}
  CODECHEF_CLIENT_SECRET: ${{ secrets.CODECHEF_CLIENT_SECRET }}
  CODEFORCES_KEY: ${{ secrets.CODEFORCES_KEY }}
  CODEFORCES_SECRET: ${{ secrets.CODEFORCES_SECRET }}

jobs:
  verify-batch-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          - codechef
          - codeforces
          - geeksforgeeks
          - hackerrank
          - leetcode

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify and Upload
        run: |
          if [[ "${{ github.event.inputs.job }}" == "all" || "${{ matrix.job }}" == "${{ github.event.inputs.job }}" ]]; then
            python main.py --batch 1 --verify ${{ matrix.job }}
          fi
      
      - name: Archive Reports
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.job }}-report-1
          path: reports/${{ matrix.job }}_handles.txt
  
  upload-batch-1:
    runs-on: ubuntu-latest
    needs: verify-batch-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Download Reports for Codechef
        uses: actions/download-artifact@v4
        with:
          name: codechef-report-1

      - name: Download Reports for Codeforces
        uses: actions/download-artifact@v4
        with:
          name: codeforces-report-1

      - name: Download Reports for GeeksforGeeks
        uses: actions/download-artifact@v4
        with:
          name: geeksforgeeks-report-1

      - name: Download Reports for HackerRank
        uses: actions/download-artifact@v4
        with:
          name: hackerrank-report-1

      - name: Download Reports for LeetCode
        uses: actions/download-artifact@v4
        with:
          name: leetcode-report-1

      - name: Move all reports to one directory
        run: |
          mkdir reports
          mv codechef*.txt codeforces*.txt geeksforgeeks*.txt hackerrank*.txt leetcode*.txt reports/

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload Reports to Database
        run: |
          python main.py --batch 1 --upload

  verify-batch-2:
    needs: verify-batch-1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          - codechef
          - codeforces
          - geeksforgeeks
          - hackerrank
          - leetcode

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify and Upload
        run: |
          if [[ "${{ github.event.inputs.job }}" == "all" || "${{ matrix.job }}" == "${{ github.event.inputs.job }}" ]]; then
            python main.py --batch 2 --verify ${{ matrix.job }}
          fi
      
      - name: Archive Reports
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.job }}-report-2
          path: reports/${{ matrix.job }}_handles.txt

  upload-batch-2:
    runs-on: ubuntu-latest
    needs: verify-batch-2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Download Reports for Codechef
        uses: actions/download-artifact@v4
        with:
          name: codechef-report-2

      - name: Download Reports for Codeforces
        uses: actions/download-artifact@v4
        with:
          name: codeforces-report-2

      - name: Download Reports for GeeksforGeeks
        uses: actions/download-artifact@v4
        with:
          name: geeksforgeeks-report-2

      - name: Download Reports for HackerRank
        uses: actions/download-artifact@v4
        with:
          name: hackerrank-report-2

      - name: Download Reports for LeetCode
        uses: actions/download-artifact@v4
        with:
          name: leetcode-report-2

      - name: Move all reports to one directory
        run: |
          mkdir reports
          mv codechef*.txt codeforces*.txt geeksforgeeks*.txt hackerrank*.txt leetcode*.txt reports/

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload Reports to Database
        run: |
          python main.py --batch 2 --upload