name: Manual Verify & Upload Users

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Choose which job to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - codechef
          - codeforces
          - geeksforgeeks
          - hackerrank
          - leetcode

env:
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  GFG_USERNAME: ${{ secrets.GFG_USERNAME }}
  GFG_PASSWORD: ${{ secrets.GFG_PASSWORD }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  CODECHEF_CLIENT_ID: ${{ secrets.CODECHEF_CLIENT_ID }}
  CODECHEF_CLIENT_SECRET: ${{ secrets.CODECHEF_CLIENT_SECRET }}
  CODEFORCES_KEY: ${{ secrets.CODEFORCES_KEY }}
  CODEFORCES_SECRET: ${{ secrets.CODEFORCES_SECRET }}

jobs:
  verify-and-upload-batch-1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        job:
          - codechef
          - codeforces
          - geeksforgeeks
          - hackerrank
          - leetcode
        os:
          - ubuntu-latest

    if: ${{ github.event.inputs.job == 'all' || github.event.inputs.job == matrix.job }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify and Upload
        run: |
          python main.py --batch 1 --verify ${{ matrix.job }} --upload

  verify-and-upload-batch-2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        job:
          - codechef
          - codeforces
          - geeksforgeeks
          - hackerrank
          - leetcode
        os:
          - ubuntu-latest

    if: ${{ github.event.inputs.job == 'all' || github.event.inputs.job == matrix.job }}

    needs: verify-and-upload-batch-1  # Ensures this runs after batch1 completes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify and Upload
        run: |
          python main.py --batch 2 --verify ${{ matrix.job }} --upload
