name: Manual Verify & Upload Users

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Choose which job to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - codechef
          - codeforces
          - geeksforgeeks
          - hackerrank
          - leetcode

env:
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  GFG_USERNAME: ${{ secrets.GFG_USERNAME }}
  GFG_PASSWORD: ${{ secrets.GFG_PASSWORD }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  CODECHEF_CLIENT_ID: ${{ secrets.CODECHEF_CLIENT_ID }}
  CODECHEF_CLIENT_SECRET: ${{ secrets.CODECHEF_CLIENT_SECRET }}
  CODEFORCES_KEY: ${{ secrets.CODEFORCES_KEY }}
  CODEFORCES_SECRET: ${{ secrets.CODEFORCES_SECRET }}

jobs:
  verify-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: [1, 2]
        job: [codechef, codeforces, geeksforgeeks, hackerrank, leetcode]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - name: Verify
        if: ${{ github.event.inputs.job == 'all' || matrix.job == github.event.inputs.job }}
        run: python main.py --batch ${{ matrix.batch }} --verify ${{ matrix.job }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.job }}-report-batch-${{ matrix.batch }}
          path: reports/${{ matrix.job }}_handles.txt

  upload-batch-1:
    needs: verify-and-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/download-artifact@v4
        with:
          pattern: *-report-batch-1
          merge-multiple: true
      - run: |
          mkdir -p reports
          mv *.txt reports/
      - run: pip install -r requirements.txt
      - run: python main.py --batch 1 --upload

  upload-batch-2:
    needs: upload-batch-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/download-artifact@v4
        with:
          pattern: *-report-batch-2
          merge-multiple: true
      - run: |
          mkdir -p reports
          mv *.txt reports/
      - run: pip install -r requirements.txt
      - run: python main.py --batch 2 --upload