name: Manual Verify & Upload Users

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Choose which job to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - codechef
          - codeforces
          - geeksforgeeks
          - hackerrank
          - leetcode
      batch:
        description: 'Specify the batch number (1, 2, or 3)'
        required: false
        default: '1'
        type: choice
        options:
          - 1
          - 2
          - 3

env:
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  GFG_USERNAME: ${{ secrets.GFG_USERNAME }}
  GFG_PASSWORD: ${{ secrets.GFG_PASSWORD }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  CODECHEF_CLIENT_ID: ${{ secrets.CODECHEF_CLIENT_ID }}
  CODECHEF_CLIENT_SECRET: ${{ secrets.CODECHEF_CLIENT_SECRET }}
  CODEFORCES_KEY: ${{ secrets.CODEFORCES_KEY }}
  CODEFORCES_SECRET: ${{ secrets.CODEFORCES_SECRET }}

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          - codechef
          - codeforces
          - geeksforgeeks
          - hackerrank
          - leetcode

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify and Upload
        run: |
          if [[ "${{ github.event.inputs.job }}" == "all" || "${{ matrix.job }}" == "${{ github.event.inputs.job }}" ]]; then
            batch_number=${{ github.event.inputs.batch }}
            python main.py --batch $batch_number --verify ${{ matrix.job }}
          fi
      
      - name: Archive Reports
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.job }}-report-${{ github.event.inputs.batch }}
          path: reports/${{ matrix.job }}_handles.txt

  upload:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Download Reports
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.verify.outputs.job }}-report-${{ github.event.inputs.batch }}

      - name: Move all reports to one directory
        run: |
          mkdir -p reports
          mv codechef*.txt codeforces*.txt geeksforgeeks*.txt hackerrank*.txt leetcode*.txt reports/

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload Reports to Database
        run: |
          batch_number=${{ github.event.inputs.batch }}
          python main.py --batch $batch_number --upload
