name: Verify & Upload Users

on:

  workflow_dispatch:
    inputs:
      job:
        description: 'Choose which job to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - codechef
          - codeforces
          - geeksforgeeks
          - hackerrank
          - leetcode
env:
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  GFG_USERNAME: ${{ secrets.GFG_USERNAME }}
  GFG_PASSWORD: ${{ secrets.GFG_PASSWORD }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  CODECHEF_CLIENT_ID: ${{ secrets.CODECHEF_CLIENT_ID }}
  CODECHEF_CLIENT_SECRET: ${{ secrets.CODECHEF_CLIENT_SECRET }}
  CODEFORCES_KEY: ${{ secrets.CODEFORCES_KEY }}
  CODEFORCES_SECRET: ${{ secrets.CODEFORCES_SECRET }}

jobs:
  codechef:
    if: ${{ github.event.inputs.job == 'all' || github.event.inputs.job == 'codechef' || github.event == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Users Codechef
        run: |
          python main.py --verify codechef

      - name: Archive Codechef Report
        uses: actions/upload-artifact@v4
        with:
          name: codechef-report
          path: reports/codechef_handles.txt
          compression-level: 9
          retention-days: 5

  codeforces:
    if: ${{ github.event.inputs.job == 'all' || github.event.inputs.job == 'codeforces' || github.event == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Users Codeforces
        run: |
          python main.py --verify codeforces

      - name: Archive Codeforces Report
        uses: actions/upload-artifact@v4
        with:
          name: codeforces-report
          path: reports/codeforces_handles.txt
          compression-level: 9
          retention-days: 5

  geeksforgeeks:
    if: ${{ github.event.inputs.job == 'all' || github.event.inputs.job == 'geeksforgeeks' || github.event == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Users GeeksforGeeks
        run: |
          python main.py --verify geeksforgeeks

      - name: Archive GeeksforGeeks Report
        uses: actions/upload-artifact@v4
        with:
          name: geeksforgeeks-report
          path: reports/geeksforgeeks_handles.txt
          compression-level: 9
          retention-days: 5

  hackerrank:
    if: ${{ github.event.inputs.job == 'all' || github.event.inputs.job == 'hackerrank' || github.event == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Users HackerRank
        run: |
          python main.py --verify hackerrank

      - name: Archive HackerRank Report
        uses: actions/upload-artifact@v4
        with:
          name: hackerrank-report
          path: reports/hackerrank_handles.txt
          compression-level: 9
          retention-days: 5

  leetcode:
    if: ${{ github.event.inputs.job == 'all' || github.event.inputs.job == 'leetcode' || github.event == 'schedule' }}
    runs-on: windows-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Users LeetCode
        run: |
          python main.py --verify leetcode

      - name: Archive LeetCode Report
        uses: actions/upload-artifact@v4
        with:
          name: leetcode-report
          path: reports/leetcode_handles.txt
          compression-level: 9
          retention-days: 5

  upload-to-db:
    needs: [codechef, codeforces, geeksforgeeks, hackerrank, leetcode]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Download Reports for Codechef
        uses: actions/download-artifact@v4
        with:
          name: codechef-report

      - name: Download Reports for Codeforces
        uses: actions/download-artifact@v4
        with:
          name: codeforces-report

      - name: Download Reports for GeeksforGeeks
        uses: actions/download-artifact@v4
        with:
          name: geeksforgeeks-report

      - name: Download Reports for HackerRank
        uses: actions/download-artifact@v4
        with:
          name: hackerrank-report

      - name: Download Reports for LeetCode
        uses: actions/download-artifact@v4
        with:
          name: leetcode-report

      - name: Print current directory structure
        run: |
          tree .

      - name: Move all reports to one directory
        run: |
          mkdir reports
          mv codechef*.txt codeforces*.txt geeksforgeeks*.txt hackerrank*.txt leetcode*.txt reports/

      - name: Print current directory structure after moving
        run: |
          tree .

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload Reports to Database
        run: |
          python main.py --upload
